version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: mongo
  backend:
    image: docker.io/moqaddas/demo_backend:latest
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb
    ports:
      - "1234:1234"
  frontend:
    image: docker.io/moqaddas/demo_frontend:latest
    container_name: frontend
    ports:
      - "80:80"

