name: CI CD Pipeline

on: 
    push:

jobs:
    build:
         runs-on: ubuntu-latest
         steps:
            - name: Clone Code
              uses: actions/checkout@v4

            - name: shell
              run: |
                    docker ps

            